apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-new
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-data-new
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
